apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workouts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: workouts
    spec:
      containers:
      - name: workouts
        image: gcr.io/mrjones-gke/workouts:v0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: workouts-google-creds
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: workouts-google-creds
              key: google-client-secret
        - name: ADMIN_GOOGLE_ID
          valueFrom:
            secretKeyRef:
              name: workouts-admin
              key: id
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: workouts-sql
              key: host
        args:
        - --google_client_id
        - $GOOGLE_CLIENT_ID
        - --google_client_secret
        - $GOOGLE_CLIENT_SECRET
        - --admin_kind
        - google
        - --admin_id
        - $ADMIN_GOOGLE_ID
        - --port
        - "8000"
        - --mysql_host
        - $MYSQL_HOST
        - --static_dir
        - /deploy/static

